"""
Output QC findings to the console (via rich) and optionally to an HTML file.
"""

from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.table import Table
from rich import box
from rich.text import Text

from .models import QCFinding, Severity

console = Console()

_SEVERITY_STYLE = {
    Severity.PASS: "bold green",
    Severity.FAIL: "bold red",
    Severity.WARN: "bold yellow",
    Severity.INFO: "bold cyan",
}

_SEVERITY_SYMBOL = {
    Severity.PASS: "✓",
    Severity.FAIL: "✗",
    Severity.WARN: "⚠",
    Severity.INFO: "ℹ",
}


def print_console_report(
    findings: list[QCFinding],
    project_label: str = "GIS QAQC",
) -> None:
    console.rule(f"[bold blue]{project_label} — QC Results[/bold blue]")

    passes = [f for f in findings if f.severity == Severity.PASS]
    fails  = [f for f in findings if f.severity == Severity.FAIL]
    warns  = [f for f in findings if f.severity == Severity.WARN]

    console.print(
        f"\n[bold]Summary:[/bold] "
        f"[green]{len(passes)} PASS[/green]  "
        f"[red]{len(fails)} FAIL[/red]  "
        f"[yellow]{len(warns)} WARN[/yellow]\n"
    )

    table = Table(box=box.SIMPLE_HEAD, show_header=True, header_style="bold")
    table.add_column("", width=2, no_wrap=True)
    table.add_column("Check", style="dim", min_width=28)
    table.add_column("Message", min_width=45)
    table.add_column("Shapefile", style="cyan", min_width=14)
    table.add_column("Report", style="magenta", min_width=14)
    table.add_column("Feature", style="dim", min_width=6)

    for f in findings:
        style = _SEVERITY_STYLE.get(f.severity, "")
        symbol = _SEVERITY_SYMBOL.get(f.severity, " ")
        table.add_row(
            Text(symbol, style=style),
            f.check_name,
            f.message,
            f.shapefile_value or "",
            f.report_value or "",
            f.feature_id or "",
            style=style if f.severity == Severity.FAIL else "",
        )

    console.print(table)

    if fails:
        console.print(f"[bold red]\n{len(fails)} issue(s) require attention.[/bold red]")
    else:
        console.print("[bold green]\nAll checks passed.[/bold green]")


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
  body {{ font-family: Arial, sans-serif; font-size: 13px; margin: 24px; color: #222; }}
  h1 {{ color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 6px; }}
  .summary {{ display: flex; gap: 24px; margin: 12px 0 20px; }}
  .badge {{ padding: 6px 14px; border-radius: 4px; font-weight: bold; font-size: 14px; }}
  .pass {{ background: #d4edda; color: #155724; }}
  .fail {{ background: #f8d7da; color: #721c24; }}
  .warn {{ background: #fff3cd; color: #856404; }}
  table {{ border-collapse: collapse; width: 100%; }}
  th {{ background: #2c3e50; color: #fff; padding: 8px 10px; text-align: left; font-size: 12px; }}
  td {{ padding: 7px 10px; border-bottom: 1px solid #ddd; vertical-align: top; }}
  tr.PASS td {{ background: #f6fff8; }}
  tr.FAIL td {{ background: #fff5f5; }}
  tr.WARN td {{ background: #fffdf0; }}
  .sev {{ font-weight: bold; width: 48px; text-align: center; }}
  .sev.PASS {{ color: #28a745; }}
  .sev.FAIL {{ color: #dc3545; }}
  .sev.WARN {{ color: #e0a800; }}
  .feature-id {{ font-family: monospace; color: #555; }}
  footer {{ margin-top: 24px; color: #888; font-size: 11px; }}
</style>
</head>
<body>
<h1>{title}</h1>
<div class="summary">
  <span class="badge pass">✓ {passes} PASS</span>
  <span class="badge fail">✗ {fails} FAIL</span>
  <span class="badge warn">⚠ {warns} WARN</span>
</div>
<table>
<thead>
  <tr>
    <th>Sev</th><th>Check</th><th>Message</th>
    <th>Shapefile Value</th><th>Report Value</th><th>Feature</th>
  </tr>
</thead>
<tbody>
{rows}
</tbody>
</table>
<footer>Generated by GIS_QAQC</footer>
</body>
</html>
"""

_ROW_TEMPLATE = """\
<tr class="{sev}">
  <td class="sev {sev}">{symbol}</td>
  <td>{check}</td>
  <td>{message}</td>
  <td>{shp}</td>
  <td>{rpt}</td>
  <td class="feature-id">{feat}</td>
</tr>"""

_SYMBOL_HTML = {
    Severity.PASS: "✓",
    Severity.FAIL: "✗",
    Severity.WARN: "⚠",
    Severity.INFO: "ℹ",
}


def _esc(text: Optional[str]) -> str:
    if not text:
        return ""
    return (text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))


def write_html_report(
    findings: list[QCFinding],
    output_path: str,
    project_label: str = "GIS QAQC",
) -> None:
    passes = sum(1 for f in findings if f.severity == Severity.PASS)
    fails  = sum(1 for f in findings if f.severity == Severity.FAIL)
    warns  = sum(1 for f in findings if f.severity == Severity.WARN)

    rows = []
    for f in findings:
        rows.append(_ROW_TEMPLATE.format(
            sev=f.severity,
            symbol=_SYMBOL_HTML.get(f.severity, ""),
            check=_esc(f.check_name),
            message=_esc(f.message),
            shp=_esc(f.shapefile_value),
            rpt=_esc(f.report_value),
            feat=_esc(f.feature_id),
        ))

    html = _HTML_TEMPLATE.format(
        title=_esc(project_label),
        passes=passes,
        fails=fails,
        warns=warns,
        rows="\n".join(rows),
    )

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(html, encoding="utf-8")
    console.print(f"[dim]HTML report written to: {output_path}[/dim]")
